apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=   # Base64 encoded value of the username
  mongo-root-password: cGFzc3dvcmQ=   # Base64 encoded value of the password

